apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-bank-app
  template:
    metadata:
      labels:
        app: flask-bank-app
    spec:
      containers:
        - name: flask-container
          image: bank_img:latest  
          imagePullPolicy: Never   
          ports:
            - containerPort: 5000  

     