apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-bank-app
  template:
    metadata:
      labels:
        app: flask-bank-app
    spec:
      containers:
      - name: flask-bank-app
        image: flask-bank-app:latest
        imagePullPolicy: Never 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
