apiVersion: v1
kind: Service
metadata:
  name: flask-bank-service
spec:
  selector:
    app: flask-bank
  ports:
    - protocol: TCP
      port: 80  # Exposed service port
      targetPort: 5000  # Flask container port
  type: LoadBalancer  
