apiVersion: v1
kind: Service
metadata:
  name: flask-e2e-service
spec:
  selector:
    app: flask-e2e
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 5000  # Flask container port
  type: LoadBalancer  # Exposes service externally (for Minikube, use NodePort)
